name: Trigger auto deployment for user-management-microservice

on:
  push:
    branches: 
      [ user-management ]
    paths:
    - '**'
    - '.github/workflows/user-management-microservice-AutoDeployTrigger-2549a059-0ed1-4f70-89de-158a9976ea68.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.USERMANAGEMENTMICROSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.USERMANAGEMENTMICROSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.USERMANAGEMENTMICROSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: sdsergiu.azurecr.io
          registryUsername: ${{ secrets.USERMANAGEMENTMICROSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERMANAGEMENTMICROSERVICE_REGISTRY_PASSWORD }}
          containerAppName: user-management-microservice
          resourceGroup: Deployment-SD
          imageToBuild: sdsergiu.azurecr.io/user-management-microservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


